config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'topics#index'

  resources :topics, except: [:new] do
  	resources :posts, only: [:create, :destroy]
  end

  resources :users, only: [:show ,:update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user
	belongs_to :topic

end

app/models/topic.rb
class Topic < ApplicationRecord

	belongs_to :user

	has_many :posts, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :topic
  has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
  	@topic = Topic.find(params[:topic_id])
  	@post = @topic.posts.new(post_params)
  	@post.user_id = current_user.id
  	if @post.save
  		redirect_to topic_path(@topic)
  	else
  	  	@topic = Topic.find(params[:id])
  		@post = Post.new
  		@posts = @topic.posts
  		render '/topics/show'
  	end

  end

  def destroy
  	@post = Post.find(params[:id])
  	if @post.user != current_user
      	redirect_to request.referer
    end
  	@post.destroy
  	redirect_back(fallback_location: root_path)
  end

	private
	def post_params
		params.require(:post).permit(:comment, :topic_id, :user_id, :handle_name)
	end
end

app/controllers/threads_controller.rb
class ThreadsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def create
  	@topic = Topic.new(topic_params)
  	@topic.user_id = current_user.id
  	if @topic.save
  		redirect_to topic_path(@topic)
  	else
  		render :new
  	end
  end

  def index
  	@topic = Topic.new
  	@topics = Topic.all
  end

  def show
  	@topic = Topic.find(params[:id])
  	@post = Post.new
  	@posts = @topic.posts
  end

  def edit
  end

  def update
  end

  def destroy
  end


  private
		def topic_params
        	params.require(:topic).permit(:title,:contents, :user_id)
      	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BBS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top" style="background-color: #6495ed;">
        <div class="row">
          <div class="col-xs-offset-1">
          <nav class="nav navbar-nav">
            <span class="site_title">
              <%= link_to '掲示板', root_path %>
            </span>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% if user_signed_in? %>
			<h4><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%>
		<% else %>
			<h4>スレッドの作成、レスの書き込みには、
				<%= link_to '会員登録', new_user_registration_path %>、
				<%= link_to 'ログイン', new_user_session_path %>が必要です。閲覧はだれでも可能です。</h4>
		<% end %>
	<% if user_signed_in? %>
		<h2>新しいスレッドを作る</h2>
		<div class="row topic_new">
			<div class="col-xs-6 topic_new_form">
			<%= form_for(@topic) do |f| %>
				<div class="field row">
					<h4>タイトル</h4>
					<%= f.text_field :title, class: "form-control col-xs-12 topic_title" %>
				</div>

				<div class="field row">
					<h4>スレッドの説明</h4>
					<%= f.text_area :contents, rows:'2', class: "form-control col-xs-12 topic_contents" %>
				</div>
				<div class="actions">
					<%= f.submit "新しいスレッドを作成", class: "btn btn-primary col-xs-5 col-xs-offset-3" %>
				</div>
			<% end %>
			</div>
		</div>
	<% end %>
		<h2>スレッド一覧</h2>
		<div class="row topic_index">
			<% @topics.each do |topic| %>
				<div class="topic_title">
					<h3><%= link_to topic_path(topic) do %>
						<%= topic.title %>
					<% end %>
					<%= topic.created_at %></h3>
					<br>
					<%= topic.contents %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/topics/show.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<h2><%= @topic.title %></h2>
		<h3><%= @topic.contents %></h3>
		<div class="row topic_show">
			<% @posts.each.with_index(1) do |post, idx| %>
			<div class="post_div">
				<P><%= idx %>　名前：
					<% if post.handle_name.present? %>
						<%= post.handle_name %>
					<% else %>
						名無しさん
					<% end %>
					<%= post.created_at %>
					<span>
						<% if user_signed_in? %>
						<% if post.user_id == current_user.id %>
						[<%= link_to '削除', topic_post_path(@topic.id, post), method: :delete, data: { confirm: '書き込みを削除してもよろしいですか？' } %>]
						<% end %>
						<% end %>
					</span>
				</P>
				<p class="post_comment"><%= post.comment %></p>
			</div>
			<% end %>
		</div>
		<% if user_signed_in? %>
		<h3>書き込み</h3>
		<div class=" row post_new">
			<%= form_for [@topic, @post] do |f| %>
				<div class="col-xs-6">
					<h4>ハンドルネーム</h4>
					<%= f.text_field :handle_name, placeholder: '入力しなかった場合「名無しさん」になります', class: "form-control" %>
					<h4>コメント</h4>
					<%= f.text_area :comment, rows:'3', class: "form-control" %>
					<%= f.submit "書き込む", class: "btn btn-primary col-xs-4 col-xs-offset-4" %>
				</div>
			<% end %>
		</div>
		<% end %>
		<div class="back_btn">
			<%= link_to 'スレッド一覧に戻る', topics_path, class: "btn btn-success" %>
		</div>
	</div>
</div>